[package]
name = "clean_xar_mounts"
version = "0.1.0"
authors = ["chip <chip@fb.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
clap = "2.31"
lazy_static = "1.0.*"
nix = "0.10.*"
regex = "0.2.*"
slog = "2.1.*"
slog-term = "2.3.*"
tempfile = "2.2.*"
